services:
  - type: web
    name: isp-billing-client
    env: static
    buildCommand: npm run build
    staticPublishPath: build
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
